application/models.py
from application import db

class Puppy(db.Model):

    __tablename__ = 'puppies'
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.Text)
    owner = db.relationship('Owner',backref='puppy',uselist=False)

    def __init__(self,name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f"Puppy name is {str(self.name).capitalize()} and owner is {self.owner.name}."
        else:
            return f"Puppy name is {str(self.name).capitalize()} and has no owner assigned yet."

class Owner(db.Model):
    __tablename__ = 'owners'

    id = db.Column(db.Integer,primary_key= True)
    name = db.Column(db.Text)
    # We use puppies.id because __tablename__='puppies'
    puppy_id = db.Column(db.Integer,db.ForeignKey('puppies.id'))

    def __init__(self,name,puppy_id):
        self.name = name
        self.puppy_id = puppy_id

application/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField


class AddOwnerForm(FlaskForm):
    name = StringField('Name of the owner: ')
    id = IntegerField('Id of the puppy to adopt: ')
    submit = SubmitField('Add Owner')

application/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):

    name = StringField('Name of Puppy:')
    submit = SubmitField('Add Puppy')

class DelForm(FlaskForm):

    id = IntegerField('Id Number of Puppy to Remove:')
    submit = SubmitField('Remove Puppy')

application/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


app = Flask(__name__)

app.config['SECRET_KEY'] = 'SECRET_KEY_OF_YOUR_CHOICE'

basedir = os.path.abspath(os.path.dirname(__file__))

app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{os.path.join(basedir,'data.sqlite')}"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)


from application.owners.views import owners_blueprint
from application.puppies.views import puppies_blueprint

app.register_blueprint(owners_blueprint,url_prefix='/owners')
app.register_blueprint(puppies_blueprint,url_prefix='/puppies')

application/owners/views.py
from flask import Blueprint, render_template, redirect, url_for
from application import db
from application.models import Owner
from application.owners.forms import AddOwnerForm


owners_blueprint = Blueprint('owners', __name__, template_folder='templates/owners')

@owners_blueprint.route('/add', methods=['GET', 'POST'])
def add():

    form = AddOwnerForm()

    if form.validate_on_submit():
        owner_name = form.name.data
        puppy_id = form.id.data

        owner = Owner(owner_name, puppy_id)
        db.session.add(owner)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('add_owner.html', form=form)

application/puppies/views.py
from flask import Blueprint, render_template, redirect, url_for
from application import db
from application.models import Puppy
from application.puppies.forms import AddForm, DelForm

puppies_blueprint = Blueprint('puppies',__name__, template_folder='templates/puppies')


@puppies_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    form = AddForm()

    if form.validate_on_submit():

        name = form.name.data

        new_pup = Puppy(name)
        db.session.add(new_pup)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('add.html', form=form)


@puppies_blueprint.route('/list')
def list():
    # Grab a list of puppies from database.
    puppies = Puppy.query.all()
    print(puppies)
    return render_template('list.html', puppies=puppies)



@puppies_blueprint.route('/delete', methods=['GET', 'POST'])
def delete():

    form = DelForm()

    if form.validate_on_submit():
        id = form.id.data
        pup = Puppy.query.get(id)
        db.session.delete(pup)
        db.session.commit()

        return redirect(url_for('puppies.list'))
    return render_template('delete.html',form=form)

application/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pup-Adopt!</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('index') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('puppies.add') }}">Add Pup</a> 
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('puppies.list') }}">List of Pups</a> 
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('puppies.delete') }}">Delete Pup</a> 
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('owners.add') }}">Add Owner</a> 
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {% block content %}
      
      {% endblock %}
      
    </body>
    </html>
    
    
    
    

application/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>Welcome to our Adoption Page</h1>
  <p>Please select one of the links from the nav bar.</p>
</div>
{% endblock %}